FROM jenkins/jenkins:lts

USER root

# Install Python, pip, and virtual environment tools needed for your backend tests
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    apt-get clean

USER jenkins
